// Realistic protein values per common serving size
export const FOOD_DATABASE = [
  { name: 'Chicken breast (6 oz)', protein: 50 },
  { name: 'Ground beef 90/10 (4 oz)', protein: 23 },
  { name: 'Steak ribeye (8 oz)', protein: 50 },
  { name: 'Salmon fillet (6 oz)', protein: 38 },
  { name: 'Tuna canned (1 can)', protein: 27 },
  { name: 'Shrimp (4 oz)', protein: 24 },
  { name: 'Eggs (2 large)', protein: 12 },
  { name: 'Egg whites (4 large)', protein: 14 },
  { name: 'Greek yogurt nonfat (1 cup)', protein: 23 },
  { name: 'Cottage cheese (1 cup)', protein: 28 },
  { name: 'Milk 2% (1 cup)', protein: 8 },
  { name: 'Cheddar cheese (1 oz)', protein: 7 },
  { name: 'Protein shake (1 scoop + water)', protein: 25 },
  { name: 'Whey protein (1 scoop)', protein: 24 },
  { name: 'Casein protein (1 scoop)', protein: 24 },
  { name: 'Turkey breast (6 oz)', protein: 48 },
  { name: 'Pork chop (6 oz)', protein: 42 },
  { name: 'Bacon (3 slices)', protein: 9 },
  { name: 'Ham deli (3 oz)', protein: 15 },
  { name: 'Tilapia (6 oz)', protein: 36 },
  { name: 'Cod (6 oz)', protein: 32 },
  { name: 'Tofu firm (4 oz)', protein: 10 },
  { name: 'Tempeh (4 oz)', protein: 22 },
  { name: 'Edamame (1 cup)', protein: 18 },
  { name: 'Lentils cooked (1 cup)', protein: 18 },
  { name: 'Black beans (1 cup)', protein: 15 },
  { name: 'Chickpeas (1 cup)', protein: 15 },
  { name: 'Quinoa cooked (1 cup)', protein: 8 },
  { name: 'Peanut butter (2 tbsp)', protein: 8 },
  { name: 'Almonds (1 oz)', protein: 6 },
  { name: 'String cheese (1 stick)', protein: 7 },
  { name: 'Pizza cheese (2 slices)', protein: 24 },
  { name: 'Burger fast food (1)', protein: 25 },
  { name: 'Chipotle chicken bowl', protein: 45 },
  { name: 'Wingstop wings (10 pc)', protein: 60 },
  { name: 'Subway turkey 6"', protein: 18 },
  { name: 'Deli turkey (3 oz)', protein: 18 },
  { name: 'Rotisserie chicken (4 oz)', protein: 30 },
  { name: 'Beef jerky (1 oz)', protein: 11 },
  { name: 'Protein bar', protein: 20 },
  { name: 'Oatmeal (1 cup cooked)', protein: 6 },
  { name: 'Rice and chicken bowl', protein: 35 },
  { name: 'Pasta with meat sauce (1 plate)', protein: 30 },
  { name: 'Steak burrito', protein: 35 },
  { name: 'Breakfast burrito', protein: 22 },
  { name: 'Overnight oats (1 cup)', protein: 15 },
  { name: 'Smoothie with protein', protein: 30 },
  { name: 'Bone broth (1 cup)', protein: 10 },
  { name: 'Shrimp stir fry (1 plate)', protein: 35 },
  { name: 'Salmon poke bowl', protein: 30 },
  { name: 'Egg + cheese bagel', protein: 17 },
  { name: 'Turkey burger (1 patty)', protein: 28 },
];
